// Generated by the Pomegranate cli on Mon Jun 10 2019

// mountPath: /

export const Routes = (Router, CaptureError) => {

  Router.get('/', (req, res, next) => {
    res.send('Hello from RestMatic!')
  })
  Router.post('/', (req, res, next) => {
    res.json({})
  })
  Router.put('/', (req, res, next) => {
    res.json({})
  })
  Router.delete('/', (req, res, next) => {
    res.json({})
  })
  
  return Router
}
